# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DESThreeTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DESThreeTest
  pod 'OpenSSL-for-iOS', '~> 1.0.2.d.1'
  
  target 'DESThreeTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
